# -*- coding: utf-8 -*-

BROWSEPATH = 'BROWSEPATH'
HEADLESS='headless'
ACK_EVENT = 'ACK_EVENT'
ACK = 'ack'
RESULT = 'result'
TID = 'targetId'
SID = 'sessionId'
ID = 'id'
METHOD = 'method'
EVENT = 'event'
OBID = 'objectId'
MSG = 'message'
SE = 'SESSION EVENT'

BLACKPAGE = 'about:blank'
LOCALHOST = 'localhost'
PARAMS = 'params'
REQPARAM = 'requestParams'
RESPPRAM = 'responseParams'
RESPLEN = 'responseLength'
ERROR = 'error'
RID = 'requestId'

Page_frameStartedLoading = 'Page.frameStartedLoading'
Page_frameStoppedLoading = 'Page.frameStoppedLoading'
Page_frameAttached = 'Page.frameAttached'
Page_frameNavigated = 'Page.frameNavigated'
Page_frameDetached = 'Page.frameDetached'
Page_domContentEventFired = 'Page.domContentEventFired'
Runtime_executionContextCreated = 'Runtime.executionContextCreated'
Runtime_executionContextDestroyed = 'Runtime.executionContextDestroyed'
Runtime_executionContextsCleared = 'Runtime.executionContextsCleared'
Page_loadEventFired = 'Page.loadEventFired'
Network_requestWillBeSent = 'Network.requestWillBeSent'
Network_loadingFinished = 'Network.loadingFinished'
Network_dataReceived = 'Network.dataReceived'
Network_responseReceived = 'Network.responseReceived'
Network_resourceChangedPriority = 'Network.resourceChangedPriority'
Network_loadingFailed = 'Network.loadingFailed'
Security_securityStateChanged = 'Security.securityStateChanged'

TIMEOUT_S = 10
MAX_PAYLOAD_SIZE_BYTES = 2 ** 23
